# Generated by Django 6.0.6 on 2026-06-17 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='tickets.ticket')),
            ],
        ),
    ]
